_wandb:
    value:
        cli_version: 0.23.0
        e:
            9z5qh3r8szdt5bmzt9czww68oxtctjvb:
                args:
                    - --dataset
                    - fashion
                    - --hidden
                    - "512"
                    - "256"
                    - --activations
                    - relu
                    - relu
                    - --optimizer
                    - adam
                    - --lr
                    - "3e-4"
                    - --batch_size
                    - "128"
                    - --epochs
                    - "20"
                    - --l2
                    - "1e-4"
                    - --weight_init
                    - he
                    - --wandb_project
                    - numpy-ffnn-group27
                cpu_count: 14
                cpu_count_logical: 20
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1022782074880"
                        used: "536721485824"
                email: jfortes@tudelft.nl
                executable: C:\Users\joluf\OneDrive\Escritorio\DL DTU\dtu-02456-numpy-ffnn-group27\.venv\Scripts\python.exe
                git:
                    commit: fac0793abd4d9ea4af6c2ea0d37453de50d15714
                    remote: https://github.com/jfortes27/dtu-02456-numpy-ffnn-group27.git
                gpu: NVIDIA RTX 3000 Ada Generation Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 4608
                      memoryTotal: "8585740288"
                      name: NVIDIA RTX 3000 Ada Generation Laptop GPU
                      uuid: GPU-dbb5f612-a1a5-c73d-6b4f-4163c28f86bd
                host: JoseLFR-HP
                memory:
                    total: "16794304512"
                os: Windows-11-10.0.26200-SP0
                program: -m src.run_experiment
                python: CPython 3.12.3
                root: C:\Users\joluf\OneDrive\Escritorio\DL DTU\dtu-02456-numpy-ffnn-group27
                startedAt: "2025-12-01T20:11:59.407150Z"
                writerId: 9z5qh3r8szdt5bmzt9czww68oxtctjvb
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 16
            "4": 3.12.3
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
activations:
    value:
        - relu
        - relu
batch_size:
    value: 128
epochs:
    value: 20
hidden:
    value:
        - 512
        - 256
l2:
    value: 0.0001
lr:
    value: 0.0003
optimizer:
    value: adam
seed:
    value: 42
wandb_project:
    value: numpy-ffnn-group27
weight_init:
    value: he
